# Generated by Django 5.0.3 on 2024-04-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDB',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=70, null=True)),
                ('Password', models.CharField(blank=True, max_length=20, null=True)),
                ('Role', models.CharField(blank=True, max_length=50, null=True)),
                ('Account_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
