# Generated by Django 5.0.3 on 2024-04-01 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDB',
            fields=[
                ('PropertyId', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(blank=True, default=None, null=True, upload_to='PropertyImage')),
                ('Purpose', models.CharField(blank=True, max_length=20, null=True)),
                ('Type', models.CharField(blank=True, max_length=20, null=True)),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Price', models.IntegerField(default=0)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.IntegerField(default=0)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REApp.registrationdb')),
            ],
        ),
    ]
