# Generated by Django 5.0.3 on 2024-04-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REApp', '0002_propertydb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='PropertyImage'),
        ),
        migrations.AlterField(
            model_name='registrationdb',
            name='Email',
            field=models.EmailField(default='aa', max_length=70),
        ),
        migrations.AlterField(
            model_name='registrationdb',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdb',
            name='Password',
            field=models.CharField(max_length=20),
        ),
    ]
