# Generated by Django 5.0.3 on 2024-04-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REApp', '0003_alter_propertydb_image_alter_registrationdb_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydb',
            name='PDF',
            field=models.FileField(blank=True, null=True, upload_to='PropertyPDF'),
        ),
    ]
