# Generated by Django 5.0.3 on 2024-04-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REApp', '0004_propertydb_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydb',
            name='Phone',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
