# Generated by Django 5.0.3 on 2024-04-22 15:12

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REApp', '0005_alter_propertydb_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydb',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
