# Generated by Django 5.0.3 on 2024-04-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REApp', '0006_alter_propertydb_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydb',
            name='Phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
