# Generated by Django 5.0.3 on 2024-04-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REApp', '0008_alter_propertydb_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Gmail', models.EmailField(max_length=254, null=True)),
                ('Message', models.CharField(max_length=250)),
            ],
        ),
    ]
